### ISSUE TITLE
Add Typescript Definition to H5P-Nodejs-Library

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Player-Nodejs-library#33]
We should add typescript definitions.

**Comment by rtens** [comment]
You wanna add Typescript Definitions although we are not using Typescript? If so: why?

**Comment by rtens** [comment]
@JPSchellenberg Ping ^

**Comment by JPSchellenberg** [comment]
You can add Typescript definitions to allow Typescript-based-projects a better integration, without using typescript yourself. For example, [immutable-js](https://github.com/immutable-js/immutable-js/blob/master/type-definitions/Immutable.d.ts) itself is written in javascript but does almost all of its documentation via Typescript. If you use immutable-js in your Typescript-project your IDE can take advantage of these definitions and provide you with information about interfaces etc.

**Comment by JPSchellenberg** [comment]
Closing this as we might switch to typescript.
