### ISSUE TITLE
Proposal: rename repository to H5P-Player-Nodejs-Library

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Player-Nodejs-library#71]
I feel like the current name is not clear regarding what this repository is containing. So to match the *H5P-Editor-Nodejs-Library*, I would like to propose to call this repo *H5P-**PLayer**-Nodejs-Library* since it only contains a library enabling to play H5P content.

What do you think, @JPSchellenberg ?

**Comment by rtens** [comment]
Any thoughts on this, @JPSchellenberg?

**Comment by JPSchellenberg** [comment]
I approve this. :) I will rename it as soon as possible.
